// TODO Add more or replace entirely the facts below for your chosen history domain
// Include at least 10 distinct facts with a 4-digit year included in the text for each
module.exports = {
    "FACTS_EN": [
        "The field of AI is considered to have its origin in 1950, with publication of British mathematician Alan Turing's paper, Computing Machinery and Intelligence.",
        "The term, Artificial Intelligence, was coined in 1956 by mathematician and computer scientist John McCarthy, at Dartmouth College, in New Hampshire.",
        "In 1997, a chess-playing program named Deep Blue, developed by IBM, beat the reigning world chess champion.",
        "A so-called AI Winter occurred in 1974, when funding was cut after Speech Understanding research did not live up to its promise.",
        "A driverless robotic car named Stanley, engineered by Sebastian Thrun's Stanford Racing team, sped through the Mojave desert at 22 miles per hour to win the 2005 Darpa Grand Challenge.",

        "The field of AI is considered to have its origin in the publication of British mathematician Alan Turing's (1912–1954) paper \"Computing Machinery and Intelligence\" (1950). The term itself was coined six years later by mathematician and computer scientist John McCarthy (b. 1927) at a summer conference at Dartmouth College in New Hampshire.",
        "Another critique of symbolic AI, advanced by Terry Winograd and Fernando Flores in their 1986 book Understanding Computers and Cognition is that human intelligence may not be a process of symbol manipulation; humans do not carry mental models around in their heads. Hubert Dreyfus makes a similar argument in Mind over Machine (1986); he suggests that human experts do not arrive at their solutions to problems through the application of rules or the manipulation of symbols, but rather use intuition, acquired through multiple experiences in the real world.",
        "He describes symbolic AI as a \"degenerating research project,\" by which he means that, while promising at first, it has produced fewer results as time has progressed and is likely to be abandoned should other alternatives become available. This prediction has proven fairly accurate. By 2000 the once dominant symbolic approach had been all but abandoned in AI, with only one major ongoing project, Douglas Lenat's Cyc (pronounced \"psych\").",
        "In 1980, John Searle, in the paper \"Minds, Brains, and Programs,\" introduced a division of the field of AI into \"strong\" and \"weak\" AI. Strong AI denoted the attempt to develop a full human-like intelligence, while weak AI denoted the use of AI techniques to either better understand human reasoning or to solve more limited problems.",
        'For a functional AI, there need be no quality labeled "intelligence" that is shared by humans and computers. All computers need do is perform a task that requires intelligence for a human to perform. It is also unnecessary, in functional AI, to model a program after the thought processes that humans use. If results are what matters, then it is possible to exploit the speed and storage capabilities of the digital computer while ignoring parts of human thought that are not understood or easily modeled, such as intuition. This is, in fact, what was done in designing the chess-playing program Deep Blue, which in 1997 beat the reigning world chess champion, Gary Kasparov.',
        'A third approach is to consider intelligence as acquired, held, and demonstrated only through relationships with other intelligent agents. In "Computing Machinery and Intelligence" (1997), Turing addresses the question of which functions are essential for intelligence with a proposal for what has come to be the generally accepted test for machine intelligence.',
        'Turing predicted that by the year 2000, there would be computers that could fool an interrogator at least thirty percent of the time. This, like most predictions in AI, was overly optimistic. No computer has yet come close to passing the Turing Test.',
        'The artificially intelligent computer in science fiction story and film is not a prop, but a character, one that has become a staple since the mid-1950s. These characters are embodied in a variety of physical forms, ranging from the wholly mechanical (computers and robots) to the partially mechanical (cyborgs) and the completely biological (androids).',
        "A general trend from the 1950s to the 1990s has been to depict intelligent computers in an increasingly anthropomorphic way. The robots and computers of early films, such as Maria in Fritz Lang's Metropolis (1926), Robby in Fred Wilcox's Forbidden Planet (1956), Hal in Stanley Kubrick's 2001: A Space Odyssey (1968), or R2D2 and C3PO in George Lucas's Star Wars (1977), were clearly constructs of metal.",
        "On the other hand, early science fiction stories, such as Isaac Asimov's I, Robot (1950), explored the question of how one might distinguish between robots that looked human and actual human beings. Films and stories from the 1980s through the early 2000s, including Ridley Scott's Blade Runner (1982) and Stephen Spielberg's A.I. (2001), pick up this question, depicting machines with both mechanical and biological parts that are far less easily distinguished from human beings.",
        "Fiction that features AI can be classified in two general categories: cautionary tales (A.I., 2001 ) or tales of wish fulfillment (Star Wars ; I, Robot ). These present two differing visions of the artificially intelligent being, as a rival to be feared or as a friendly and helpful companion."
    ]
}