// TODO Add more or replace entirely the facts below for your chosen history domain
// Include at least 10 distinct facts with a 4-digit year included in the text for each
module.exports = {
    "FACTS_EN": [
        "The field of AI is considered to have its origin in 1950, with publication of British mathematician Alan Turing's paper, Computing Machinery and Intelligence.",
        "The term, Artificial Intelligence, was coined in 1956 by mathematician and computer scientist John McCarthy, at Dartmouth College, in New Hampshire.",
        "In 1997, a chess-playing program named Deep Blue, developed by IBM, beat the reigning world chess champion.",
        "A so-called AI Winter occurred in 1974, when funding was cut after Speech Understanding research did not live up to its promise.",
        "A driverless robotic car named Stanley, engineered by Sebastian Thrun's Stanford Racing team, sped through the Mojave desert at 22 miles per hour to win the 2005 Darpa Grand Challenge.",

        "One thing that you may have noticed when it comes to AI that you possibly interact with, like Google Now, Siri, and Cortana, that the default voice is female. For the record, this isn’t one of the terrifying facts; we just find it fascinating that AI tends to be female. Why is that, exactly?",
        "Pets are great, but they have a number of downsides. You have to clean up after them, they can be destructive, they need to be fed, and of course, they die. Something that will take care of all those downsides is AI driven pets. University of Melbourne animal welfare researcher Dr. Jean-Loup Rault says that there are already a number of patents for robot pets and they could be widely available by 2025.",
        "On the terrifying end of the spectrum, there was a paper published this year about a robot that could rebuild itself, even after losing two of its six legs. The robot doesn’t know what’s broken, but notices that its performance has dropped. Then, using an algorithm based on trial and error, the robot can figure out what’s wrong and how to repair itself. The researchers who developed the robot said that as it fixes itself, it updates its database with all the things that will not work in a phase called “simulated childhood.”",
        "A question that’s bound to arise is that if AI is almost or completely indistinguishable from humans, will humans be able to have physical and emotional relationships with AI entities? David Levy at the University of Maastricht in the Netherlands had an interesting, but plausible, scenario where sex with a robot could become more mainstream. He said that at first it will come across as geeky, but then a story will appear in a publication like Cosmo in which someone will rave about how great sex with a robot is, and the mainstream attention could alter the prevailing attitudes.",
        "There’s a saying about computers that they’re only as smart as the person using them. However, with advancements with AI, computers are starting to learn by themselves. For example, Google developed an AI system that taught itself to play Atari 2600 games. After doing so, it beat some of the world’s best players.",
        "With AI having the ability to learn, computers are getting to be pretty smart. As of 2013, AI was about at the same intelligence level as a four-year-old and there have been lots of advances since then. For example, in 2014 a supercomputer cracked a complicated math problem called Erdos discrepancy problem, which was published in 1930. The amazing thing is that humans can’t even double check the solution because the equation is too long. The file is 13-gigabytes, and just for comparison, all of Wikipedia is about 10-gigbytes.",
        "An interesting development in artificial intelligence is an SGI Altix supercomputer called Nautilus. It appears that, to a certain degree, Nautlius can predict the future. For example, it was able to predict where Osama bin Laden was hiding within 125 miles, and was also able to predict the Arab Spring that started in December of 2010.",
        "There’s little doubt that AI has the potential to greatly improve our lives. AI will make the roads safer, help in medicine, aide the disabled and the elderly, work customer service and a number of countless other jobs. However, AI also poses an incredible threat, and this isn’t the stuff of science fiction, either. Top scientists and technologists like Stephen Hawking, Bill Gates and Elon Musk believe that AI is a very real, and dangerous threat to humankind.",
        "A British mathematician by the name of Alan Turing is one of the founding fathers on theory and development of Artificial Intelligence. In the 1950’s he invented a test (aptly called the Turing Test) to prove if a machine exhibits artificial Intelligence. The test calls for a human evaluator to judge a natural language conversation with a machine. Based on questions the bot answers, the evaluator would determine if it exhibited behavior intelligent enough to be equivalent to, or indistinguishable from, that of a human. ",
        "Fast forward to 1996 when IBM’s Deep Blue lost to Russian chess master Gary Kasparov (don’t feel bad though, as Deep Blue finally prevailed in 1997). Deep Blue was solely designed by IBM to beat Mr. Kasparov at his own game. I don’t know what seems crazier, the fact that a machine could calculate 200 million possible chess positions a second or that Gary Kasparov was capable of outwitting that machine.",
        "The success of Deep Blue spawned IBM’s Watson super computer, which was specially designed to compete against Jeopardy’s all-time champions (which it beat). One of the challenges with Watson was programming it to understand questions in common language and answer them quickly. Today, Watson is enjoying a career in several industries, including most recently, helping people learn how to cook amazing recipes.",
        "There are actually a few different types of artificial intelligence and one of them is called Expert Systems. This type of artificial intelligence is knowledge based and is designed to display and mimic aspects of intelligent behavior. Ultimately, the goal behind this type of A.I. is to imitate human capabilities of sensing and cognition. The video games millions of people enjoy on a daily basis employ this type of A.I.",
        "Video game A.I. is a bit one dimensional in that you have to visit a console and play a game to interact with it. Sony’s Aibo was one of the first “toys” you could buy and actually interact with. Aibo is a robotic dog that can explore, play and express both sadness and happiness. One of its unique traits was that it could even recognize its owner! For a modern and much more expensive version, check out Softbank’s Pepper humanoid robot.",
        "Autonomous vehicles are starting to become a mainstream topic in the news these days. This future of transportation relies on artificial intelligence to recognize and adapt to driving conditions and behavior. There are numerous governments in the US and Europe that have green lit patches of road to test these systems and validate them. That nap on the way home from work is closer than you think!",
        "There is an artificial intelligence arms race heating up between social media companies. Facebook and Twitter are two companies using A.I. to match people to relevant content on their respective sites. Google has been one of the pioneers in perfecting the use of A.I. to pair people with what they are looking for.",
        "There are many experts who are concerned by A.I., including Tesla founder Elon Musk — he just recently publicized his $10 million dollar investment in 37 research projects to make sure A.I. never gets the upper hand.",
        "You might interact with artificial intelligence way more than you think. There are hundreds of millions of them out there. This includes personalized assistants on our cell phones like Siri and Cortana. We use them to find as movie times and a gas station nearby or weather forecasts.",
        "Our future is undeniably intertwined with artificial intelligence, so where does it go from here? It is inevitable that it will surpass a human’s ability to do many things but most of those things will also improve how we live. The promise of something called Quantum Artificial Intelligence would harness A.I. for advanced cures in medicine or mapping even more of the universe. NASA has a Quantum Artificial Intelligence Lab that is currently working to formally assess the potential of these systems.",
    ]
}